env:
  global:
    - CC_TEST_REPORTER_ID=956483eed1687c95ec558190633c49d7414ae331842e5c51d4d75934a5656889
language : node_js
node_js: '8'

addons:
  apt:
    update: true

services :
  - postgresql

postgres:
  adapter: postgresql
  database: DB_DATABASE
  username: postgres

before_script:
  - psql -c 'create database travisData;' -U postgres
  - chmod 0777 ./node_modules/.bin/mocha
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success: npm run coverage